# Generated by Django 4.0.4 on 2022-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
